baseURL = "https://example.com/"
title = "hw_insight"
defaultContentLanguage = "ko"

[markup.goldmark.renderer]
  unsafe = true

[module]
  [[module.imports]]
    path = "github.com/thishw/synapse-hugo-shared"
